- .gitignore
- default.nix
- selda-postgresql/default.nix
- selda-sqlite/default.nix
- selda-tests/default.nix
- selda/default.nix
Nix is great for building multiple Haskell packages. These additions can live alongside the existing `Makefile` and CI system. Simply call `nix-build`, and all packages will be built, tested and haddock'd. If you'd like to use nix for uploading to `hackage` that's possible too (or for testing multiple GHCs on TravisCI).
To build with a different GHC: `nix-build --argstr compiler ghc7103`
```shell
λ nixos selda → λ git nixify → nix-build
/nix/store/ngs0ksf6vvip04h69msiggdxqm6sa0wm-selda-0.1.0.0
/nix/store/nc0fvzqn88mljrd3zlb2awnd1yvzl5kb-selda-postgresql-0.1.0.0
/nix/store/s4nkgphjgmy9wfy56p25055ln5xkriz6-selda-sqlite-0.1.0.0
/nix/store/y6g2vv7cbvwz9yipa07l59mw38vbkzjd-selda-tests-0.1.0.0
```
If you want to develop your `selda` packages in an isolated shell,
```nix-shell -A selda.env``` …
> Add nix build scripts

- selda/selda.cabal
This is needed to allow installation with Stack's lts-6.31, which is the latest release that comes with ghc 7.10.3.
That LTS release comes with an older version of the time package (1.5.1.0). Selda compiles just fine with that version, so I suppose it would work just as well.
> Loosen the version constraint on the time package

- selda/src/Database/Selda/SqlType.hs
This would be pretty handy for me, since I want to pull some `RowID`s out of some query results and put them into `Set`s and `Map`s.
Feel free to close this if you don't want the instance, or if there are reasons why this would be bad.
> Add an `Ord` instance for `RowID`.

- selda-tests/test/Tests/Query.hs
- selda/src/Database/Selda.hs
- selda/src/Database/Selda/Column.hs
- selda/src/Database/Selda/Exp.hs
- selda/src/Database/Selda/SQL/Print.hs
This implementation is probably not perfect. And I wasn't sure about how to name things.
But I was curious about how this would be implemented, and this only took a few minutes :)
> Add ifThenElse

- selda-postgresql/src/Database/Selda/PostgreSQL.hs
- selda/src/Database/Selda/SQL/Print/Config.hs
- selda/src/Database/Selda/Table/Compile.hs
Since DDL differs from database to database I've added a hook that will take generated field definition and allow for more flexible post processing. It works on raw generated text but it should provide enough flexibility for now until API is reworked a bit more (also it's a bit cleaner than my previous attempt).
> Added a hook in to PPConfig to allow for more flexibility when generating fields.

- selda/src/Database/Selda/Generic.hs
I changed it because the double quotes produce broken links in the haddocks.
> Fix haddock markup in genTableFieldMod.

- selda/src/Database/Selda/Generic.hs
Addresses https://github.com/valderman/selda/issues/72, i.e:
```
test :: ((Int, Float, Double), (Text, (Text, Float)))
test = fromRel (5 :*: 5 :*: 5 :*: "text" :*: "text2" :*: 2.0)
```
Not entirely sure whether that's the best way to set up the `GFromRel` instances. Another one would be to say `a` instead of `f a` in  `instance {-# OVERLAPPABLE #-} (Generic (f a), GFromRel (Rep (f a))) => (GFromRel (K1 i (f a))) where`, but then we'd need individual instances for `String`, `Float` and so on. `f a` captures some random constructor (i.e. `(,)`), but breaks down on `[Char]`. `Text` works.
> Nested GFromRel instance

- selda/src/Database/Selda.hs
- selda/src/Database/Selda/Column.hs
- selda/src/Database/Selda/Exp.hs
- selda/src/Database/Selda/Query.hs
- selda/src/Database/Selda/SQL/Print.hs
- selda/src/Database/Selda/Unsafe.hs
this may be less than ideal, I don't really like exporting `random` as a simple column because its use is more restricted than that, and it can't be given a concrete type here since `random()`'s return type differs between postgres (double) and sqlite (64-bit int). usecase is to be able to do `order random ascending`
> Add nullary function support

- selda-postgresql/src/Database/Selda/PostgreSQL.hs
It seems you accidentally left a `putStrLn` in the code. This MR deletes that line.
> Remove debugging line.

- selda-postgresql/src/Database/Selda/PostgreSQL.hs
- selda-sqlite/src/Database/Selda/SQLite.hs
- selda/src/Database/Selda/Backend/Internal.hs
- selda/src/Database/Selda/Table.hs
- selda/src/Database/Selda/Table/Compile.hs
- selda/src/Database/Selda/Validation.hs
continuation from #111
Not sure how to "make sure the validation and migration machinery takes TableInfo.tablePkGroups into account."
> Allow multiple primary keys - continued

- selda-postgresql/src/Database/Selda/PostgreSQL.hs
Currently tableUniqueGroups (from the database) always comes back with an empty list.
The type of tableUniqueGroups has changed making the list comprehension fail.
The code looked significantly different for SQLite and I didn't have a look at if it was broken there too.
> fix issue where tableUniqueGroups would always come back as []

- ChangeLog.hs
- selda-json/selda-json.cabal
- selda-postgresql/selda-postgresql.cabal
- selda-sqlite/selda-sqlite.cabal
- selda-tests/test/Tables.hs
- selda-tests/test/Tests/Mutable.hs
- selda-tests/test/Tests/Validation.hs
- selda/selda.cabal
- selda/src/Database/Selda/Table.hs
- selda/src/Database/Selda/Table/Compile.hs
- selda/src/Database/Selda/Table/Type.hs
- selda/src/Database/Selda/Types.hs
Indexes used to be generated by looking at the column attributes for an `Indexed` column, which limited the design to a single selector.  The new method stores indexes in the table attributes which are then used by `compileCreateIndex`.
API
The api for indexes has changed from accepting a Selector to a Group. Thus code that used to appear `[col :- index]` might now need to be `[Single col :- index]`.  With the advantage that we can now say `[(Single col2 :+ Single col1) :- index]`.
The version of selda has been bumped in response to this API change.
Uniqueness
Index names are constructed by from the column names, which are recovered by looking up each column info based on index. Any underscores in the column name is escaped ("column_name" ~~> "column__name") and all columns are joined …
> Add multicolumn index support.

- selda/src/Database/Selda.hs
I find that exposing the table name from the table data type is very convenient and I can't see any downsides with exposing it
> Expose tableName from Table

- selda/src/Database/Selda/Frontend.hs
This adds a note to the comment for `withoutForeignKeyEnforcement` encouraging use of deferred foreign key constraints.
Relates to #57
> Add note to `withoutForeignKeyEnforcement` encouraging deferred constraints.

- selda-postgresql/src/Database/Selda/PostgreSQL.hs
- selda-postgresql/src/Database/Selda/PostgreSQL/Encoding.hs
- selda-sqlite/src/Database/Selda/SQLite.hs
- selda/src/Database/Selda/Backend/Internal.hs
- selda/src/Database/Selda/SQL/Print/Config.hs
- selda/src/Database/Selda/SqlType.hs
- selda/src/Database/Selda/Validation.hs
In mostly an answer to https://williamyaoh.com/posts/2019-12-14-typesafe-db-libraries.html and my own eventual needs, here is some firming up of Int32 and Int64 support.
> Add distinction between int 64 and int 32.

- selda-postgresql/src/Database/Selda/PostgreSQL/Encoding.hs
- selda-tests/test/Tests/Query.hs
- selda/src/Database/Selda/Query.hs
Fix #165 by removing isolate from `distinct` calls.
Recall that queries in the form:
```
borked :: Query s (Col s Int)
borked = aggregate $ do
_ <- distinct $ do
t <- select people
pure (t ! #msg)
x <- distinct $ do
t <- select people
pure (t ! #name)
pure (count x)
```
Cause Selda + the psql backend to fail.  For a complete program see #165 and a throw-away psql such as `docker run -p 5432:5432 --rm -e POSTGRES_PASSWORD=password -d postgres`.
This query now succeeds along with `make test` and the `make pgtest` target.  That said, I don't claim to have shoved the whole selda design into my head so viewing the PR with some suspicion is warranted.
> Do not isolate `distinct` to avoid missing renames

- selda/src/Database/Selda/Backend/Internal.hs
> SeldaT uses a ReaderT instead of StateT

- selda/src/Database/Selda.hs
- selda/src/Database/Selda/SqlRow.hs
I'm only exporting the class name, not its methods.
That's useful when doing Generic hackery in client libraries. For instance I'm derivating Tables out of vinyl records, and in order to make Rec an instance to SqlRow, I need to refer to `GSqlRow`.
> Exporting GSqlRow to be able to refer to it

- selda-postgresql/src/Database/Selda/PostgreSQL.hs
- selda-sqlite/src/Database/Selda/SQLite.hs
- selda/src/Database/Selda/Backend/Internal.hs
This adds a field to `TableInfo` for holding the `TableName`.
This fixes https://github.com/valderman/selda/issues/147.
I tested this by running `make test`, but I didn't run the postgresql-specific tests (hopefully this is tested in CI?)
> Add tableInfoName field to TableInfo that holds the TableName from Table

- .gitignore
- selda-json/selda-json.cabal
- selda-postgresql/selda-postgresql.cabal
- selda-sqlite/selda-sqlite.cabal
- selda-tests/selda-tests.cabal
- selda-tests/test/Tests/Mutable.hs
- selda/selda.cabal
- stack-ghc-9.0.yaml
- stack-ghc-9.2.yaml
The first 2 commits will allow selda packages to be used together with GHC 9.0, GHC 9.2 and newer versions of aeson, bytestring, random & time. The second 2 commits are for development ergonomics.
> Enable compatibility with newer GHC and dependency versions

- selda-postgresql/src/Database/Selda/PostgreSQL.hs
Closes #182 
This makes two changes
- Order the column by their actual ordering when querying the structure
- Add the schema where relevant when querying table information
> Fix schema query for validation in postgres case

- selda/src/Database/Selda/Backend/Internal.hs
- selda/src/Database/Selda/Generic.hs
- selda/src/Database/Selda/SQL/Print.hs
- selda/src/Database/Selda/SqlRow.hs
- selda/src/Database/Selda/Unsafe.hs
That's only import fixs, some symbol from `base` are not reexported by `mtl` anymore. This commit uses the version from `base` instead.
> fix: build with mtl 2.3 and ghc 9.6
